# Generated by Django 3.2.9 on 2021-11-23 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('short_stories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'verbose_name_plural': 'stories'},
        ),
    ]
