# Generated by Django 3.2.9 on 2021-11-23 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short_stories', '0002_alter_story_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='cover',
            field=models.ImageField(default=1, upload_to='covers/'),
            preserve_default=False,
        ),
    ]
