# Generated by Django 3.2.9 on 2021-12-01 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short_stories', '0002_alter_story_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='cover',
            field=models.URLField(),
        ),
    ]
