# Generated by Django 3.2.9 on 2021-11-24 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('short_stories', '0003_story_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='cover',
        ),
    ]
