# Generated by Django 3.2.9 on 2021-11-26 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short_stories', '0004_remove_story_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='cover',
            field=models.ImageField(default=1, upload_to='media/'),
            preserve_default=False,
        ),
    ]
