# Generated by Django 3.2.9 on 2021-11-25 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short_stories', '0005_story_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='genre',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
